version: "0.1"
services:
  app:
    container_name: tpdne-app
    build: .
    env_file:
      - .env
    environment:
      - DJANGO_DB_HOST=database
    ports:
      - '8000:8000'
    depends_on:
      - database
  database:
    image: postgres:15.2-bullseye
    container_name: tpdne-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DJANGO_DB_NAME}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - PGPORT=${DJANGO_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DJANGO_DB_PORT}:${DJANGO_DB_PORT}"

volumes:
  postgres-data: