# Generated by Django 5.0.7 on 2024-07-12 15:41

import gallery.constants
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=gallery.constants.ImageType.choices,
                        default=gallery.constants.ImageType["HUMAN"],
                        max_length=50,
                    ),
                ),
                ("_image", models.ImageField(upload_to=gallery.models._image_path)),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to=gallery.models._preview_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
